# docker-compose.override.yml
services:
  webserver:
    build: .
    depends_on:
      - metabase  # start Metabase too so setup can run

  scheduler:
    build: .

  triggerer:
    build: .

  metabase:
    image: metabase/metabase:v0.52.8.4
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./include/data/metabase:/metabase-data
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - postgres